name: 12 - Working with Ouputs

on:
    workflow_dispatch:
         inputs:
             building-status:
                     type: choice
                     options:
                       - success
                       - failure
                     default: success
  
jobs:
    build:
         runs-on: ubuntu-latest
         outputs:
             result: ${{ steps.build.outputs.result }}
         steps:
             - name: Build
               id: build
               run: echo "results=${{inputs.building-status}}" >> "$GITHUB_OUTPUT"
  
    deploy:
         runs-on: ubuntu-latest
         needs: build
         steps:
               - name: Deploy
                 if: ${{needs.build.outputs.result == 'success'}}
                 run: echo "Deploying"
