name: 12 - Working with Ouputs

on: 
     workflow_dispatch:
         inputs:
             building-status:
                     type: choice
                     options:
                       - success
                       - failure
                     default: success  

jobs:
     build:
         runs-on: ubuntu-latest
         outputs:
              build-status: ${{ steps.build.outputs.status }}    
         steps:
               - name: Print GITHUB_OUTPUT path
                 run: echo "$GITHUB_OUTPUT"
               - name: Build
                 id: build
                 # "<key> = <value>" >> "$GITHUB_OUTPUT" to store in outputs
                 run: echo "status = ${{ inputs.building-status }}" >> "$GITHUB_OUTPUT"
               - name:  Print GITHUB_OUTPUT path2
                 run: echo "${{ steps.build.outputs.status }} "

     deploy:
         runs-on: ubuntu-latest
         needs: build
         if: ${{needs.build.outputs.build-status == 'success'}} 
         steps:
              - name: Deploy
                run: echo "Deploying"            
