name: 12 - Working with Ouputs

on:
    workflow_dispatch:
         inputs:
             building-status:
                     type: choice
                     options:
                       - success
                       - failure
                     default: success
  
jobs:
    build:
         runs-on: ubuntu-latest
         outputs:
             results: ${{ steps.build.outputs.results }}
         steps:
             - name: Build
               id: build
               run: echo "results = success" >> "$GITHUB_OUTPUT"
  
    deploy:
         runs-on: ubuntu-latest
         needs: build
         steps:
               - name: Deploy
                 if: ${{needs.build.outputs.results == 'success'}}
                 run: echo "Deploying"
