name: 12 - Working with Ouputs

on:
    push:
      branches:
        - main
  
jobs:
    build:
         runs-on: ubuntu-latest
         outputs:
             result: ${{ steps.build.outputs.result }}
         steps:
             - name: Build
               id: build
               run: echo "result=success" >> "$GITHUB_OUTPUT"
  
    deploy:
         runs-on: ubuntu-latest
         needs: build
         if: ${{needs.build.outputs.result == 'success'}}
         steps:
               - name: Deployment
                 env:
                   BUILD_STATUS: ${{ needs.build.outputs.result }}
                 run: echo "Deploying"
