name: 13 - Using Caching

on:
    workflow_dispatch:
         inputs:
             use-cache:
                 description: Whether to execute cache step
                 type: boolean
                 default: true
             node-version: 
                 description: Node version
                 type: choice
                 options:
                    - 16.x
                    - 18.x
                    - 20.x
                    - 22.x
                 default: 16.x   

jobs:
    install-deps:
         runs-on: ubuntu-latest
         defaults:
          run:
             working-directory: 13-caching/react-app
         outputs:
            deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}   

         steps:
          #1. Checkout the code
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Setup Node
            uses: actions/setup-node@v3
            with: 
                 node-version: ${{ inputs.node-version }}
          - name: Download cache key
            id: cache-key
            run: |
               echo "CACHE_KEY = deps-node-modules-${{ hashFiles('13-caching/react-app/packaqge-lock.json') }}" >> "GITHUB_OUTPUT"
          # Download cache dependencies
          - name: Download cached dependencies
            uses: actions/cache@v3
            if: ${{ inputs.use-cache }}
            id: cache
            with:
                 path: 13-caching/react-app/node-modules
                 key: ${{ steps.cache-key.outputs.CACHE_KEY }}     
          #2. install dependecies       
          - name: Install dependencies
            if: steps.cache.outputs.cache-hit != 'true'
            run: npm ci     

    lint-test:
         runs-on: ubuntu-latest
         needs: install-deps
         defaults:
             run:
                working-directory: 13-caching/react-app

         steps:
             #1. Checkout the code
             - name: Checkout code
               uses: actions/checkout@v4
             - name: Setup Node
               uses: actions/setup-node@v3
               with: 
                    node-version: '${{ inputs.node-version }}'
             # Download cache dependencies
             - name: Download cache dependencies
               uses: actions/cache@v3
               if: ${{ inputs.use-cache }}
               id: cache
               with:
                    path: 13-caching/react-app/node-modules
                    key: ${{ needs.install-deps.outputs.deps-cache-key }}
             - name: Install dependencies
               if: steps.cache.outputs.cache-hit != 'true'
               run: npm ci         
             - name: Testing
               run: npm run test 
             - name: Linting
               run: echo "Linting"
    
    build: 
         runs-on: ubuntu-latest
         needs: install-deps
         defaults:
             run:
                working-directory: 13-caching/react-app

         steps:
             #1. Checkout the code
             - name: Checkout code
               uses: actions/checkout@v4
             - name: Setup Node
               uses: actions/setup-node@v3
               with: 
                    node-version: '${{ inputs.node-version }}'
             # Download cache dependencies
             - name: Download cache dependencies
               uses: actions/cache@v3
               if: ${{ inputs.use-cache }}
               id: cache
               with:
                    path: 13-caching/react-app/node-modules
                    key: ${{ needs.install-deps.outputs.deps-cache-key }}
             - name: Install dependencies
               if: steps.cache.outputs.cache-hit != 'true'
               run: npm ci    
             - name: Building
               run: npm run build
              #4. Deploy to a nonprod env 
             - name: Deploying to nonprod
               run: echo "Deploying to nonprod"           






      