name: 17 - Custom actions - JS
run-name: 17 - 1 - Custom Actions - JS | BB - ${{inputs.base-branch}} TB - ${{ inputs.traget-branch}} WD - ${{inputs.working-dir}}

on:
    workflow_dispatch: 
        inputs:
            base-branch:
                type: string
                default: main
            traget-branch:
                type: string
                default: update-dependencies
            working-dir:
                type: string
                default: 17-custom-actions/react-app


env:
     working-directory: 17-custom-actions/react-app

jobs:
     dependency-update:
         runs-on: ubuntu-latest
         steps:
            - uses: actions/checkout@v4       
            - name: Check for dependency updates
              uses: ./.github/actions/js-dependency-update
              with:
                basebranch: ${{ inputs.base-branch }}
                target-branch: ${{ inputs.traget-branch }}
                working-directory: ${{inputs.working-dir}}
             